name: dicex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main
      - name: eda
        uses: actions/checkout@main
        with:
          repository: wulffern/eda
          path: eda
      - run: pip3 install --user -r requirements.txt
      - run: echo "${HOME}/eda/bin" >> $GITHUB_PATH
      - name: Run programs
        run: source eda/bashrc && make test
