name: dicex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: dicex
      - name: eda
        uses: actions/checkout@master
        with:
          repository: wulffern/eda
          path: dicex/eda
      - name: Run programs
        run: source dicex/eda/bashrc && cd dicex/ make test
